/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfazGrafica;

import excepciones.PersistenciaException;
import interfaces.IClientesDAO;
import interfaces.ICuentasDAO;
import interfaces.IDireccionesClientesDAO;
import interfaces.IRetirosDAO;
import interfaces.ITransferenciasDAO;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author march
 */
public class FrmDepositar extends javax.swing.JFrame {

    private static final Logger LOG = Logger.getLogger(FrmDepositar.class.getName());
    private final IClientesDAO clientesDAO;
    private final IDireccionesClientesDAO direccionesClientesDAO;
    private final ICuentasDAO cuentasDAO;
    private final IRetirosDAO retirosDAO;
    private final ITransferenciasDAO transferenciasDAO;
    private float cantidadAgregada;
    private boolean operacion;

    public FrmDepositar(IClientesDAO clientesDAO, IDireccionesClientesDAO direccionesClientesDAO, ICuentasDAO cuentasDAO, IRetirosDAO retirosDAO, ITransferenciasDAO transferenciasDAO) {
//        ImageIcon icon = new ImageIcon(getClass().getResource("/multimedia/iconCaballoPerfil.png"));
//        this.setIconImage(icon.getImage());
        this.setTitle("BANCO POTROS");
        this.clientesDAO = clientesDAO;
        this.direccionesClientesDAO = direccionesClientesDAO;
        this.cuentasDAO = cuentasDAO;
        this.retirosDAO = retirosDAO;
        this.transferenciasDAO = transferenciasDAO;
        this.cantidadAgregada = 0f;
        this.operacion = true;
        initComponents();
        this.txtCantidad.setText(String.valueOf(cantidadAgregada));
    }

    public void agregarDinero() {
        try {
            this.cuentasDAO.sumarSaldo(this.txtNumeroTarjeta.getText(), cantidadAgregada);
            this.mostrarMensajeDineroAgregado();
        } catch (PersistenciaException e) {
            this.mostrarMensajeErrorAlAgregar();
        }
    }

    private void mostrarMensajeDineroAgregado() {
        JOptionPane.showMessageDialog(
                this,
                "Cantidad agregada exitosamente",
                "Información",
                JOptionPane.INFORMATION_MESSAGE);
    }

    private void mostrarMensajeErrorAlAgregar() {
        JOptionPane.showMessageDialog(
                this,
                "No fue posible agregar la cantidad ingresada.",
                "Error",
                JOptionPane.ERROR_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn50 = new javax.swing.JButton();
        btn100 = new javax.swing.JButton();
        btn200 = new javax.swing.JButton();
        btn500 = new javax.swing.JButton();
        btn1000 = new javax.swing.JButton();
        btn2000 = new javax.swing.JButton();
        txtCantidad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSumar = new javax.swing.JButton();
        btnRestar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNumeroTarjeta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn50.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn50.setForeground(new java.awt.Color(0, 153, 255));
        btn50.setText("$ 50");
        btn50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn50ActionPerformed(evt);
            }
        });
        jPanel1.add(btn50, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 80, 40));

        btn100.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn100.setForeground(new java.awt.Color(0, 153, 255));
        btn100.setText("$ 100");
        btn100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn100ActionPerformed(evt);
            }
        });
        jPanel1.add(btn100, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 80, 40));

        btn200.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn200.setForeground(new java.awt.Color(0, 153, 255));
        btn200.setText("$ 200");
        btn200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn200ActionPerformed(evt);
            }
        });
        jPanel1.add(btn200, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 80, 40));

        btn500.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn500.setForeground(new java.awt.Color(0, 153, 255));
        btn500.setText("$ 500");
        btn500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn500ActionPerformed(evt);
            }
        });
        jPanel1.add(btn500, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 90, 40));

        btn1000.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn1000.setForeground(new java.awt.Color(0, 153, 255));
        btn1000.setText("$ 1000");
        btn1000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1000ActionPerformed(evt);
            }
        });
        jPanel1.add(btn1000, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, 40));

        btn2000.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn2000.setForeground(new java.awt.Color(0, 153, 255));
        btn2000.setText("$ 2000");
        btn2000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2000ActionPerformed(evt);
            }
        });
        jPanel1.add(btn2000, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, -1, 40));

        txtCantidad.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel1.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 100, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Saldo a depositar");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, -1, -1));

        btnAgregar.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, -1, -1));

        btnCancelar.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        btnCancelar.setText("Regresar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));

        btnSumar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSumar.setText("Sumar");
        btnSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumarActionPerformed(evt);
            }
        });
        jPanel1.add(btnSumar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 90, 50));

        btnRestar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRestar.setText("Restar");
        btnRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRestar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 90, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/potros-itson-chico.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Seleccione la cantidad");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Número de Tarjeta");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, -1, -1));
        jPanel1.add(txtNumeroTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 140, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn50ActionPerformed
        if (operacion) {
            this.cantidadAgregada += 50;
            this.txtCantidad.setText(String.valueOf(cantidadAgregada));
        } else {
            if (this.cantidadAgregada >= 50) {
                this.cantidadAgregada -= 50;
                this.txtCantidad.setText(String.valueOf(cantidadAgregada));
            } else {
                this.cantidadAgregada = 0;
                this.txtCantidad.setText(String.valueOf(cantidadAgregada));
            }
        }
    }//GEN-LAST:event_btn50ActionPerformed

    private void btn100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn100ActionPerformed
        if (operacion) {
            this.cantidadAgregada += 100;
            this.txtCantidad.setText(String.valueOf(cantidadAgregada));
        } else {
            if (this.cantidadAgregada >= 100) {
                this.cantidadAgregada -= 100;
                this.txtCantidad.setText(String.valueOf(cantidadAgregada));
            } else {
                this.cantidadAgregada = 0;
                this.txtCantidad.setText(String.valueOf(cantidadAgregada));
            }
        }
    }//GEN-LAST:event_btn100ActionPerformed

    private void btn200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn200ActionPerformed
        if (operacion) {
            this.cantidadAgregada += 200;
            this.txtCantidad.setText(String.valueOf(cantidadAgregada));
        } else {
            if (this.cantidadAgregada >= 200) {
                this.cantidadAgregada -= 200;
                this.txtCantidad.setText(String.valueOf(cantidadAgregada));
            } else {
                this.cantidadAgregada = 0;
                this.txtCantidad.setText(String.valueOf(cantidadAgregada));
            }
        }
    }//GEN-LAST:event_btn200ActionPerformed

    private void btn500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn500ActionPerformed
        if (operacion) {
            this.cantidadAgregada += 500;
            this.txtCantidad.setText(String.valueOf(cantidadAgregada));
        } else {
            if (this.cantidadAgregada >= 500) {
                this.cantidadAgregada -= 500;
                this.txtCantidad.setText(String.valueOf(cantidadAgregada));
            } else {
                this.cantidadAgregada = 0;
                this.txtCantidad.setText(String.valueOf(cantidadAgregada));
            }
        }
    }//GEN-LAST:event_btn500ActionPerformed

    private void btn1000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1000ActionPerformed
        if (operacion) {
            this.cantidadAgregada += 1000;
            this.txtCantidad.setText(String.valueOf(cantidadAgregada));
        } else {
            if (this.cantidadAgregada >= 1000) {
                this.cantidadAgregada -= 1000;
                this.txtCantidad.setText(String.valueOf(cantidadAgregada));
            } else {
                this.cantidadAgregada = 0;
                this.txtCantidad.setText(String.valueOf(cantidadAgregada));
            }
        }
    }//GEN-LAST:event_btn1000ActionPerformed

    private void btn2000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2000ActionPerformed
        if (operacion) {
            this.cantidadAgregada += 2000;
            this.txtCantidad.setText(String.valueOf(cantidadAgregada));
        } else {
            if (this.cantidadAgregada >= 2000) {
                this.cantidadAgregada -= 2000;
                this.txtCantidad.setText(String.valueOf(cantidadAgregada));
            } else {
                this.cantidadAgregada = 0;
                this.txtCantidad.setText(String.valueOf(cantidadAgregada));
            }
        }
    }//GEN-LAST:event_btn2000ActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(this, "¿Desea regresar?", "REGRESAR", JOptionPane.YES_NO_OPTION);
        if (respuesta == JOptionPane.YES_OPTION) {
            FrmInicio inicio = new FrmInicio(clientesDAO, direccionesClientesDAO, cuentasDAO, retirosDAO, transferenciasDAO);
            inicio.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumarActionPerformed
        this.operacion = true;
    }//GEN-LAST:event_btnSumarActionPerformed

    private void btnRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestarActionPerformed
        this.operacion = false;
    }//GEN-LAST:event_btnRestarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        this.agregarDinero();
        FrmInicio inicio = new FrmInicio(clientesDAO, direccionesClientesDAO, cuentasDAO, retirosDAO, transferenciasDAO);
        inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAgregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn100;
    private javax.swing.JButton btn1000;
    private javax.swing.JButton btn200;
    private javax.swing.JButton btn2000;
    private javax.swing.JButton btn50;
    private javax.swing.JButton btn500;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRestar;
    private javax.swing.JButton btnSumar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtNumeroTarjeta;
    // End of variables declaration//GEN-END:variables
}
